In [1]:
import pandas as pd

# Mengenal DataFrame

In [2]:
minuman = pd.DataFrame(data={'Beverages' : ['Coffe', 'Milk', 'Syrup'],
                  'Price ( $ )' : [2, 1.4, 0.8]})

In [3]:
minuman.to_csv('C:\Dataset\minuman.csv', index=False)

In [4]:
pd.DataFrame(data  = {'Companies' : ['Tesla', 'Alphabet', 'Facebook', 'Microsoft'],
                     'Birthplace' : ['South Africa', 'US', 'US', 'US']}, 
                   index = ['Elon Musk','Larry Page','Mark Zuckerberg','Bill Gates'])

                 Companies    Birthplace
Elon Musk            Tesla  South Africa
Larry Page        Alphabet            US
Mark Zuckerberg   Facebook            US
Bill Gates       Microsoft            US

# Mengenal Series

In [5]:
pd.Series(data = [3,4,7,10])

0     3
1     4
2     7
3    10
dtype: int64

In [6]:
pd.Series(data = [1,3,5,7,9], index = ['one','three','five','seven','nine'], name = 'Odd Number')

one      1
three    3
five     5
seven    7
nine     9
Name: Odd Number, dtype: int64

# Memuat file CSV

In [7]:
wine_df = pd.read_csv('C:\Dataset\winemag-data-130k-v2.csv', index_col = 0)
wine_df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [8]:
wine_df.shape

(129971, 13)

# Melakukan akses data pada DataFrame

Terdapat dua mekanisme untuk melakukan akses data pada DataFrame: index-based colection dan label-based colection.
Kedua mekanisme ini mendahului baris ( row ) lalu kolom ( column )

1. Index-based colection

In [9]:
wine_df.iloc[:3,:3].head()

    country                                        description   designation
0     Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco
1  Portugal  This is ripe and fruity, a wine that is smooth...      Avidagos
2        US  Tart and snappy, the flavors of lime flesh and...           NaN

In [10]:
wine_df.iloc[[0,3,4],[0,5]]

  country           province
0   Italy  Sicily & Sardinia
3      US           Michigan
4      US             Oregon

In [11]:
wine_df.iloc[-4:,[0,5]]

       country province
129967      US   Oregon
129968  France   Alsace
129969  France   Alsace
129970  France   Alsace

2. label based selection

In [12]:
wine_df.loc[2:5,['country','province']]

  country        province
2      US          Oregon
3      US        Michigan
4      US          Oregon
5   Spain  Northern Spain

In [13]:
wine_df[['country','province']][:2]

    country           province
0     Italy  Sicily & Sardinia
1  Portugal              Douro

# Men-set index

In [14]:
wine_df.set_index('country').head()

,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,
Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [15]:
wine_df.reset_index().head(3)

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

# Seleksi data pada DataFrame

In [16]:
wine_df['country'] == 'US'

0         False
1         False
2          True
3          True
4          True
          ...
129966    False
129967     True
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [17]:
wine_df.loc[wine_df['country'] == 'US'].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma,Virginie Boone,@vboone,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini

In [18]:
wine_df[(wine_df['country'] == 'US') & (wine_df['price'] > 30)].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma,Virginie Boone,@vboone,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini
19,US,"Red fruit aromas pervade on the nose, with cig...",NaN,87,32.0,Virginia,Virginia,NaN,Alexander Peartree,NaN,Quiévremont 2012 Meritage (Virginia),Meritage,Quiévremont
25,US,Oak and earth intermingle around robust aromas...,King Ridge Vineyard,87,69.0,California,Sonoma Coast,Sonoma,Virginie Boone,@vboone,Castello di Amorosa 2011 King Ridge Vineyard P...,Pinot Noir,Castello di Amorosa
33,US,"Rustic and dry, this has flavors of berries, c...",Puma Springs Vineyard,86,50.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Envolve 2010 Puma Springs Vineyard Red (Dry Cr...,Red Blend,Envolve

# Beberapa method built-in

method isin

In [19]:
wine_df.loc[wine_df['country'].isin(['US', 'Italy'])].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo

method isna dan notna

In [20]:
wine_df[wine_df['region_1'].isna()].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
15,Germany,Zesty orange peels and apple notes abound in t...,Devon,87,24.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Richard Böcking 2013 Devon Riesling (Mosel),Riesling,Richard Böcking
36,Chile,"White flower, lychee and apple aromas carry th...",Estate,86,15.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Estampa 2011 Estate Viognier-Chardonnay (Colch...,Viognier-Chardonnay,Estampa
44,Chile,A berry aroma comes with cola and herb notes. ...,NaN,86,9.0,Maule Valley,NaN,NaN,Michael Schachner,@wineschach,Sundance 2011 Merlot (Maule Valley),Merlot,Sundance

In [21]:
wine_df[wine_df['region_2'].notna()].head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma,Virginie Boone,@vboone,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini
14,US,Building on 150 years and six generations of w...,NaN,87,12.0,California,Central Coast,Central Coast,Matt Kettmann,@mattkettmann,Mirassou 2012 Chardonnay (Central Coast),Chardonnay,Mirassou

# Menambah kolom pada DataFrame

In [22]:
wine_df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

In [23]:
wine_df['store_name'] = 'Cigarette & Black'
wine_df['store_name'].head()

0    Cigarette & Black
1    Cigarette & Black
2    Cigarette & Black
3    Cigarette & Black
4    Cigarette & Black
Name: store_name, dtype: object

In [24]:
wine_df.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery', 'store_name'],
      dtype='object')

In [25]:
wine_df['index_backwards'] = range(len(wine_df), 0, -1)
wine_df[['index_backwards', 'country']].tail()

        index_backwards  country
129966                5  Germany
129967                4       US
129968                3   France
129969                2   France
129970                1   France

# Menghasilkan summary pada DataFrame

In [26]:
wine_df.describe()

              points          price  index_backwards
count  129971.000000  120975.000000    129971.000000
mean       88.447138      35.363389     64986.000000
std         3.039730      41.022218     37519.540256
min        80.000000       4.000000         1.000000
25%        86.000000      17.000000     32493.500000
50%        88.000000      25.000000     64986.000000
75%        91.000000      42.000000     97478.500000
max       100.000000    3300.000000    129971.000000

In [27]:
wine_df['price'].describe()

count    120975.000000
mean         35.363389
std          41.022218
min           4.000000
25%          17.000000
50%          25.000000
75%          42.000000
max        3300.000000
Name: price, dtype: float64

In [28]:
wine_df['country'].describe()

count     129908
unique        43
top           US
freq       54504
Name: country, dtype: object

In [29]:
wine_df['taster_name'].unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [30]:
wine_df['country'].value_counts().head()

US          54504
France      22093
Italy       19540
Spain        6645
Portugal     5691
Name: country, dtype: int64

# Methode Mapping

1. method map ( diterapkan pada series )

In [31]:
points_mean = wine_df['points'].mean()
wine_df['points'].map(lambda x: x - points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

2. method apply ( diterapkan di DataFrame)

In [32]:
def remean_points(row):
    row['points'] = row['points'] -  points_mean
    return row

wine_df.apply(remean_points, axis=1).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,store_name,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Cigarette & Black,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Cigarette & Black,129970
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Cigarette & Black,129969
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Cigarette & Black,129968
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Cigarette & Black,129967

# Alternatif akses built-in method

In [33]:
points_mean = wine_df['points'].mean()
points_mean - wine_df['points']

0         1.447138
1         1.447138
2         1.447138
3         1.447138
4         1.447138
            ...
129966   -1.552862
129967   -1.552862
129968   -1.552862
129969   -1.552862
129970   -1.552862
Name: points, Length: 129971, dtype: float64

In [34]:
wine_df['country'] + ' - ' + wine_df['region_1'] + ', ' + wine_df['region_2']

0                                               NaN
1                                               NaN
2         US - Willamette Valley, Willamette Valley
3                                               NaN
4         US - Willamette Valley, Willamette Valley
                            ...
129966                                          NaN
129967                    US - Oregon, Oregon Other
129968                                          NaN
129969                                          NaN
129970                                          NaN
Length: 129971, dtype: object

# Mencari title_name dengan proporsi points/price tertinggi dan terendah

In [35]:
wine_df.loc[(wine_df['price']/wine_df['points']).idxmax(), 'title']

'Château les Ormes Sorbet 2013  Médoc'

In [36]:
wine_df.loc[(wine_df['price']/wine_df['points']).idxmin(), 'title']

'Bandit NV Merlot (California)'

In [37]:
wine_df['title'][(wine_df['points']/wine_df['price']).idxmax()]

'Bandit NV Merlot (California)'

In [38]:
wine_df['title'][(wine_df['points']/wine_df['price']).idxmin()]

'Château les Ormes Sorbet 2013  Médoc'

Kasus : mencari jumlah wine dengan description tropical dan fruity. Siapkan series untuk menampung jumlah data

In [39]:
n_tropical = wine_df['description'].map(lambda x: 'tropical' in x).sum()
n_fruity   = wine_df['description'].map(lambda x: 'fruity' in x).sum()
pd.Series([n_tropical, n_fruity], index=['tropical','fruity'])

tropical    3607
fruity      9090
dtype: int64

# melakukan konversi point menjadi star

In [43]:
def converter(row):
    if row['country'] == 'US':
        row['star'] = 3
    elif row['country'] == 'Italy':
        row['star'] = 3.5
    elif row['points'] >= 92:
        row['star'] = 2.8
    elif row['points'] >= 85:
        row['star'] = 2.5
    else :
        row['star'] = 1
    return row

wine_df['star'] = None
wine_df.apply(converter, axis=1).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,store_name,index_backwards,star
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Cigarette & Black,129971,3.5
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Cigarette & Black,129970,2.5
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Cigarette & Black,129969,3.0
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Cigarette & Black,129968,3.0
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Cigarette & Black,129967,3.0

# Analisis terhadap sekelompok data

In [46]:
wine_df['points'].value_counts().tail()

80     397
97     229
98      77
99      33
100     19
Name: points, dtype: int64

In [49]:
wine_df.groupby('points')['points'].count().tail()

points
96     523
97     229
98      77
99      33
100     19
Name: points, dtype: int64

In [52]:
wine_df['taster_name'].value_counts().head()

Roger Voss           25514
Michael Schachner    15134
Kerin O’Keefe        10776
Virginie Boone        9537
Paul Gregutt          9532
Name: taster_name, dtype: int64

In [68]:
wine_df.groupby('country')['price'].min().tail()

country
Switzerland    21.0
Turkey         14.0
US              4.0
Ukraine         6.0
Uruguay        10.0
Name: price, dtype: float64

In [78]:
wine_df.groupby('country').apply(lambda x : x[x['points'] == x['points'].max()])['title'].head()

country
Argentina               82754     Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
Armenia                 66146           Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia               345       Chambers Rosewood Vineyards NV Rare Muscat (Ru...
Austria                 109406    Kracher 2008 Zwischen den Seen Nummer 9 Trocke...
Bosnia and Herzegovina  96759                   Winery Čitluk 2011 Blatina (Mostar)
Name: title, dtype: object

In [80]:
wine_df.groupby(['country', 'province']).apply(lambda x : x[x['points'] == x['points'].max()])['title'].head(10)

country    province
Argentina  Mendoza Province   82754    Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
           Other              78303                   Colomé 2010 Reserva Malbec (Salta)
Armenia    Armenia            66146          Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia  Australia Other    37882    Marquis Philips 2000 Sarah's Blend Red (South ...
           New South Wales    85337    De Bortoli 2007 Noble One Bortytis Semillon (N...
           South Australia    56953        Penfolds 2010 Grange Shiraz (South Australia)
           Tasmania           76216                 Tolpuddle 2014 Chardonnay (Tasmania)
           Victoria           345      Chambers Rosewood Vineyards NV Rare Muscat (Ru...
           Western Australia  87137    Moss Wood 2011 Cabernet Sauvignon (Margaret Ri...
Austria    Austria            39456    Kracher NV Nouvelle Vague Nummer 4 Kollektion ...
Name: title, dtype: object

# Aggregat

In [82]:
wine_df.groupby('country')['price'].agg([len,max,min]).head()

                           len     max   min
country
Argentina               3800.0   230.0   4.0
Armenia                    2.0    15.0  14.0
Australia               2329.0   850.0   5.0
Austria                 3345.0  1100.0   7.0
Bosnia and Herzegovina     2.0    13.0  12.0

In [83]:
wine_df.groupby('variety')['price'].agg(['min','max','mean']).head()

              min    max       mean
variety
Abouriou     15.0   75.0  35.000000
Agiorgitiko  10.0   66.0  23.571429
Aglianico     6.0  180.0  38.887755
Aidani       27.0   27.0  27.000000
Airen         8.0   10.0   9.000000

In [93]:
wine_df.sort_values(by='price',ascending=False).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,store_name,index_backwards,star
80290,France,This ripe wine shows plenty of blackberry frui...,NaN,88,3300.0,Bordeaux,Médoc,NaN,Roger Voss,@vossroger,Château les Ormes Sorbet 2013 Médoc,Bordeaux-style Red Blend,Château les Ormes Sorbet,Cigarette & Black,49681,None
15840,France,The wine is a velvet glove in an iron fist. Th...,NaN,96,2500.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Château Pétrus 2014 Pomerol,Bordeaux-style Red Blend,Château Pétrus,Cigarette & Black,114131,None
98380,France,"A superb wine from a great year, this is power...",NaN,96,2500.0,Burgundy,La Romanée,NaN,Roger Voss,@vossroger,Domaine du Comte Liger-Belair 2010 La Romanée,Pinot Noir,Domaine du Comte Liger-Belair,Cigarette & Black,31591,None
120391,US,The nose on this single-vineyard wine from a s...,Roger Rose Vineyard,91,2013.0,California,Arroyo Seco,Central Coast,Matt Kettmann,@mattkettmann,Blair 2013 Roger Rose Vineyard Chardonnay (Arr...,Chardonnay,Blair,Cigarette & Black,9580,None
113564,France,"A wonderfully complete wine, with all the elem...",NaN,96,2000.0,Burgundy,La Romanée,NaN,Roger Voss,@vossroger,Domaine du Comte Liger-Belair 2005 La Romanée,Pinot Noir,Domaine du Comte Liger-Belair,Cigarette & Black,16407,None

In [94]:
wine_df_simple = wine_df[['country','price','province','title']]

In [98]:
wine_df_simple.sort_values(by='price',ascending=False).head()

,country,price,province,title
80290,France,3300.0,Bordeaux,Château les Ormes Sorbet 2013 Médoc
15840,France,2500.0,Bordeaux,Château Pétrus 2014 Pomerol
98380,France,2500.0,Burgundy,Domaine du Comte Liger-Belair 2010 La Romanée
120391,US,2013.0,California,Blair 2013 Roger Rose Vineyard Chardonnay (Arr...
113564,France,2000.0,Burgundy,Domaine du Comte Liger-Belair 2005 La Romanée

In [99]:
wine_df_simple.sort_values(['country','title'],ascending=False).head()

,country,price,province,title
117371,Uruguay,15.0,Atlantida,Viñedo de los Vientos 2016 Estival White (Atla...
6969,Uruguay,23.0,Atlantida,Viñedo de los Vientos 2012 Eolo Gran Reserva R...
10581,Uruguay,40.0,Atlantida,Viñedo de los Vientos 2008 Angel's Cuvée Ripas...
27115,Uruguay,10.0,Juanico,Pueblo del Sol 2013 Tannat (Juanico)
48543,Uruguay,10.0,Juanico,Pueblo del Sol 2010 Tannat (Juanico)

Menampilkan daftar harga terendah dan tertinggi untuk setiap variety wine, data diurutkan secara descending berdasarkan harga terendah dan diikuti harga tertinggi

In [105]:
wine_df.groupby('variety')['price'].agg(['min','max']).sort_values(['min','max']).head()

                    min    max
variety
Pinot Grigio        4.0   70.0
Malbec-Syrah        4.0   78.0
White Blend         4.0  375.0
Tempranillo         4.0  600.0
Cabernet Sauvignon  4.0  625.0

Menampilkan rata-rata points yang diberikan taster_name

In [106]:
wine_df.groupby('taster_name')['points'].mean().head()

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Name: points, dtype: float64

menampilkan jumlah wine ( title ) yang dihasilkan tiap negara ( country ) untuk setiap jenis wine ( variety )

In [113]:
wine_df.groupby(['country','variety'])['title'].value_counts().sort_values(ascending=False).head()

country  variety          title
US       Sparkling Blend  Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma County)     11
                          Korbel NV Brut Sparkling (California)                       9
Spain    Sparkling Blend  Segura Viudas NV Extra Dry Sparkling (Cava)                 8
                          Segura Viudas NV Aria Estate Extra Dry Sparkling (Cava)     7
US       Sparkling Blend  Gloria Ferrer NV Blanc de Noirs Sparkling (Carneros)        7
Name: title, dtype: int64

# Mengubah nama kolom pada DataFrame

In [115]:
wine_df.rename(columns={'points': 'score'}).head()

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,store_name,index_backwards,star
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Cigarette & Black,129971,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Cigarette & Black,129970,None
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Cigarette & Black,129969,None
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Cigarette & Black,129968,None
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Cigarette & Black,129967,None

In [120]:
wine_df.rename_axis('index',axis=1)

index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,store_name,index_backwards,star
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Cigarette & Black,129971,None
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Cigarette & Black,129970,None
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Cigarette & Black,129969,None
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Cigarette & Black,129968,None
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Cigarette & Black,129967,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),Cigarette & Black,5,None
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,Cigarette & Black,4,None
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,Cigarette & Black,3,None
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,Cigarette & Black,2,None
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,Cigarette & Black,1,None